# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`isa`
	:runtime-requirement    [ :on "perl 5.006"^^:CpanId ];
	:runtime-requirement    [ :on "Scalar::Util"^^:CpanId ];
	:runtime-recommentation [ :on "Type::Tiny::XS"^^:CpanId ];
	:test-requirement       [ :on "Test::More 0.96"^^:CpanId ];
	:develop-recommendation [ :on "Dist::Inkt 0.001"^^:CpanId ];
	.

